### ISSUE TITLE
data templates for datasets

### ISSUE THREAD

**Issue by sgratzl** [arclamp/materialnet#67]
> Design a system to display different  data templates for different datasets.

@waxlamp can you elaborate on that?

**Comment by waxlamp** [comment]
The idea is that different datasets may require different types of custom data displays. We will need a mechanism to somehow select data display templates as different datasets are selected.

This issue isn't quite actionable yet, as I'll need to process the co-occurrence dataset so it can be displayed in the app alongside the ones that are there already, but I will work on this and discuss with you when it's ready.
